### ISSUE TITLE
Can we move this to material-foundation?

### ISSUE THREAD

**Issue by appsforartists** [material-motion/gh#1]

**Comment by jverkoey** [comment]
We need to turn this in to a proper fork and then move our forked branch over to the fork.

**Comment by appsforartists** [comment]
That seems easy enough.  Can't you just add the material-foundation as a remote, rebase to it, push to it, and delete this repo?

**Comment by jverkoey** [comment]
Didn't say it was hard :) Sometimes I be busy though.

I'd recommend just clicking the "fork" button on the gh repo and forking it to material-motion. You can then do all the branch pushing from this repo to that and then delete this repo as you said.

**Comment by appsforartists** [comment]
Wanna add me to material-foundation?  I can just do it to your fork there.

**Comment by jverkoey** [comment]
Invite sent.

**Comment by jverkoey** [comment]
Ah, also keep in mind that we'll have to update the submodule in https://github.com/material-motion/material-motion-team.

**Comment by appsforartists** [comment]
Done.
